# Use the official Python base image with version 3.11.2
FROM python:3.11.8

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port on which the Flask API will run
EXPOSE 5000

# Set the entrypoint command to run the Flask API
CMD [ "flask", "run", "--host", "0.0.0.0"]